name = "Invictus"
author = "InstaSnipe"
version = "2.0-b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f5d6bffe2a7ea8bf78f28fad00923922bf0ba9be7f78a4a4ae6143649420be0"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
