name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85c08670827dbb5f831757a29644134afaedb4c916f841ac7622e143ca0ef77e"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
