name = "Invictus"
author = "InstaSnipe"
version = "0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca2cde629589731d169a18d69b5b7d40be7aaa6e876c6a2d3c94fc5719495292"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
