name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "789b5d93aaea258230ca5207c713e26667b33b89dcdda7d255ea1263d4c15504"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
