name = "Invictus"
author = "InstaSnipe"
version = "0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12c5f5fae751b681725ba400e00fdcc48af80bafda68dc72d0bd5233ab87bbff"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
