name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef1f515c75361dbeb9d62e2384cd8f47709f4b14f653f008188eebf195631f4a"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
