name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ae60a8cb6ddb6e2538a045bf9015a123c32ffbe0086e38ecdb03a0c7691fb4d"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
