name = "Invictus"
author = "InstaSnipe"
version = "0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93face12f1272cf47183ab3b568f281e730fbd4310b753573c3ed28d74252ac8"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
