name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ec3eb165b25bb04f8588861da61cedc61e8dc9c25a261dbfd4729f8ff80b77d"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
