name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a6011fe37126c19c96230897db1881784e7c060ce8d31ddb2bc8b3fd7a958a5"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
