name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f1fa3e04f367d08478adb54be9b3bc3c15dd5b5d3ecdf27497049de9f26c677"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
