name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f49bbfbe5af6bfce4b26c21e5fbaea1df923ac4d09500a4177a62827da9cc81"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
