name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd16a66a18f9f7a9d7b018a1cf8ae650314c87324de35e52f84a7e54f93d64af"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
