name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf243b36750ef964d7d6324f3bee9fe5faa6dbdba31c3e45e21a8246b091f03d"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
