name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af5dd7081dd77735866cf9f3341672ef191b82a07c822e78eede9aa1036ae70c"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
