name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56d85bbcc3b2621d1ace8804a55d4d1fe55ad1001f835153486df485e7238acb"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
