name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "230de4155d388f519e4ff48e4791a21cb12f0b3b89ab11ff2220af41b7e8c319"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
