name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cacf7a462b52479c93d388d69565de9b0c0240949bdedb83a6144f18198c927f"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
