name = "Invictus"
author = "InstaSnipe"
version = "0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d25b1580a21efbea128a75798f73c61475841865343f7e5f0cb89eaa3daf1eb2"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
