name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67a6fa3dda694e308658a61afc743a3239a0bd0292ad8823fcc517438be04b99"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
