name = "Invictus"
author = "InstaSnipe"
version = "0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ebc35030923abe14254f1e39959e1dae37e9e9959fbe910ce14ea9126e9c51d"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
