name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2b25600b647a43cfd054c3bfaee334bc2dd6b17f4dea4b6d9741358c9ed2221"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
