name = "Invictus"
author = "InstaSnipe frfr"
version = "2.0-a.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6faa0120b86cde3cc03509243b84173ef06cc93b28ecc2fc3b86d879a0c090c3"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
