
#World generation settings for Mekanism. This config is synced from server to client
[world_generation]
	#Allows chunks to retrogen Mekanism ore blocks.
	enableRegeneration = false
	#Change this value to cause Mekanism to regen its ore in all loaded chunks.
	#Range: > 0
	userWorldGenVersion = 0

	#Generation Settings for tin ore.
	[world_generation.tin]
		#Determines if tin ore should be added to world generation.
		shouldGenerate = false

	#Generation Settings for osmium ore.
	[world_generation.osmium]
		#Determines if osmium ore should be added to world generation.
		shouldGenerate = false

	#Generation Settings for uranium ore.
	[world_generation.uranium]
		#Determines if uranium ore should be added to world generation.
		shouldGenerate = false

	#Generation Settings for fluorite ore.
	[world_generation.fluorite]
		#Determines if fluorite ore should be added to world generation.
		shouldGenerate = false

	#Generation Settings for lead ore.
	[world_generation.lead]
		#Determines if lead ore should be added to world generation.
		shouldGenerate = false
		
	#Generation Settings for salt.
	[world_generation.salt]
		#Determines if salt should be added to world generation.
		shouldGenerate = false
		

