
#Friends
[friends]
	#A list of users who can be chosen when it spawns a distant friend
	friends = ["darkosto", "slimeyar", "instasnipe", "nullharp", "t8rt0t", "2m80", "likzerd"]
	#Add the players from the whitelist to the Friends list [default: true]
	addWhitelistPlayers = true

#Spawning
[spawning]
	#The spawning weight of Friend's (0 = disabled) [default: 20]
	#Range: > 0
	friendWeight = 10
	#The minimum number of Friend's in a group [default:1]
	#Range: > 1
	friendMinGroup = 1
	#The maximum number of Friend's in a group [default: 2]
	#Range: > 1
	friendMaxGroup = 4

#Compat
[compat]
	#Add players from a Player Mobs whitelist to the Friends list [default: false]
	playerMobsCompat = false
	#The player mobs Name Links
	playerMobsWhitelist = [""]

